USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF10;
-- SELECT * FROM CUSTOMER;

SELECT C_MKTSEGMENT, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER
GROUP BY C_MKTSEGMENT
ORDER BY CUSTOMER_COUNT DESC;

-- SELECT COUNT(DISTINCT C_CUSTKEY) AS unique_customer_count
-- FROM CUSTOMER;